window.onload = RandomPRCharacter;

function RandomPRCharacter() {

  var PRcharacters = [
    ["Aileen", "Aleksander", "Alilith", "Allon", "Altair", "Amadeus", "Amias", "Aphi'im", "Arcadia", "Arrow", "Ashyr", "Beet", "Bellerose", "Beni", "Bonnie", "Bright", "Calypso", "Clairee", "Cole", "Cricket", "Cyrus", "Dakota", "Damon", "Denali", "Diona", "Dog", "Double A", "Douglas", "Eaden", "Elijah", "Enzo", "Euanthe", "Everett", "Fenre", "Finch", "Fisher", "Fleet", "Florian", "Greyson", "Hannelore", "Holly", "Hoshi", "Ivah", "Jason", "Jebediah Bolt", "Jehu", "Judas", "Kaulu", "Lichen", "Lucreta", "Marauder", "Mateo", "Mavikus", "Melchior", "Milky", "Mirte", "Monty", "Morrow", "Murmim", "Muttonchops", "Nayelli", "Neak", "Nitro", "Oliver", "Omen", "Orin", "Osmani", "Phantom", "Phexis", "Pidge", "Pine", "Pyrite", "Red", "River", "Saga", "Shale", "Shiloh", "Shrike", "Sokoros", "Spencer", "Syaoran", "Thea", "Theo", "Willow", "Wolf", "Wren", "Zinnia"],
    ["http://fav.me/dcyyvrh", "http://fav.me/dcz06vg", "http://fav.me/dcz6usv", "http://fav.me/dd3esg3", "http://fav.me/dcyxo1o", "http://fav.me/dczvtew", "http://fav.me/dcz0l05", "http://fav.me/dd3gbjb", "http://fav.me/dcz6kri", "http://fav.me/dcz6nmx", "http://fav.me/dd2guxe", "http://fav.me/dczbej8", "https://www.deviantart.com/ice-galaxy/art/PR-Bellerose-792074616", "http://fav.me/dcyzvjp", "http://fav.me/dcz51ro", "http://fav.me/dd0193t", "http://fav.me/dd33q0c", "https://www.deviantart.com/roosprouting/art/PR-Clairee-826729785", "http://fav.me/dczgd6b", "http://fav.me/dcyz35d", "http://fav.me/dcz2bho", "http://fav.me/dd0u7ng", "http://fav.me/dcz6e6x", "http://fav.me/dcz0am7", "http://fav.me/dd2va3c", "http://fav.me/dcyyn6y", "http://fav.me/dcz5ess", "http://fav.me/dcyznlb", "http://fav.me/dd33cmt", "http://fav.me/dd2bwxj", "http://fav.me/dd0py1h", "http://fav.me/dd3lq6l", "http://fav.me/dcyx73i", "http://fav.me/dd2s9up", "https://www.deviantart.com/ninjaespy/art/Paradise-Rising-Finch-784764740", "http://fav.me/dd3g0ai", "http://fav.me/dcz0nd4", "http://fav.me/dczhvlf", "https://www.deviantart.com/sinful-souls/art/PR-Greyson-789488969", "http://fav.me/dd3ldd4", "http://fav.me/dd1vziu", "http://fav.me/dcz5xtl", "http://fav.me/dd3956n", "http://fav.me/dcz4mtc", "http://fav.me/dd2v7b1", "http://fav.me/dcyxgmt", "http://fav.me/dd3k72z", "http://fav.me/dd3cqmy", "http://fav.me/dd1vzlt", "http://fav.me/dd33n93", "http://fav.me/dcyzrkh", "http://fav.me/dd6hxd1", "http://fav.me/dd3isb4", "http://fav.me/dcyyydi", "http://fav.me/dcywkda", "http://fav.me/dd2b14x", "http://fav.me/dcz3q4h", "http://fav.me/dd2aewc", "http://fav.me/dd1tj1s", "http://fav.me/dd2ekbj", "http://fav.me/dd2mq7o", "http://fav.me/dd14a76", "http://fav.me/dd3fnnz", "http://fav.me/dcyy81j", "http://fav.me/dd2ndzm", "http://fav.me/dcz2m5u", "http://fav.me/dd39b36", "http://fav.me/dcyxi98", "http://fav.me/dd39t2z", "http://fav.me/dd0da08", "http://fav.me/dcz3hbj", "http://fav.me/dcz8yfh", "http://fav.me/dd3i625", "http://fav.me/dcyzpb0", "http://fav.me/dd0mlyy", "http://fav.me/dd3hzit", "http://fav.me/dd1r9k2", "http://fav.me/dcz23e4", "http://fav.me/dd3ez65", "http://fav.me/dd1uytn", "http://fav.me/dcyw3sr", "http://fav.me/dd0db91", "http://fav.me/dcz3dmw", "http://fav.me/dd3li0t", "http://fav.me/dd0vse9", "http://fav.me/dcz05lh", "http://fav.me/dcyx2jr"]
  ];

  var choose = Math.floor(Math.random() * PRcharacters[0].length);

  CharacterName = PRcharacters[0][choose];
  CharacterSheet = PRcharacters[1][choose];

  document.querySelector("#cat").innerHTML = CharacterName + " " + "<a href='" + CharacterSheet + "' target='_blank'>Sheet</a>");

}
